export const GET_NOW_PLAYING = 'GET_NOW_PLAYING';
export const STORE_NOW_PLAYING = 'STORE_NOW_PLAYING';
export const GET_CONFIGURATION = 'GET_CONFIGURATION';
export const STORE_CONFIGURATION = 'STORE_CONFIGURATION';
export const GET_GENRES = 'GET_GENRES';
export const STORE_GENRES = 'STORE_GENRES';
